Microsoft Windows [Version 10.0.19045.4170]
(c) Microsoft Corporation. All rights reserved.

C:\Users\RockNutria>cd djangogirls

C:\Users\RockNutria\djangogirls>git init
Initialized empty Git repository in C:/Users/RockNutria/djangogirls/.git/

C:\Users\RockNutria\djangogirls>git config --global user.name "RockNutria"

C:\Users\RockNutria\djangogirls>git config --global user.email zacharymbergman@gmail.com

C:\Users\RockNutria\djangogirls>git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore
        blog/
        manage.py
        mysite/
        requirements.txt

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\RockNutria\djangogirls>git add .

C:\Users\RockNutria\djangogirls>git commit -m "My Django Girls app, first commit"
[master (root-commit) 791db87] My Django Girls app, first commit
 16 files changed, 299 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 blog/__init__.py
 create mode 100644 blog/admin.py
 create mode 100644 blog/apps.py
 create mode 100644 blog/migrations/0001_initial.py
 create mode 100644 blog/migrations/__init__.py
 create mode 100644 blog/models.py
 create mode 100644 blog/tests.py
 create mode 100644 blog/views.py
 create mode 100644 manage.py
 create mode 100644 mysite/__init__.py
 create mode 100644 mysite/asgi.py
 create mode 100644 mysite/settings.py
 create mode 100644 mysite/urls.py
 create mode 100644 mysite/wsgi.py
 create mode 100644 requirements.txt

C:\Users\RockNutria\djangogirls>git remote add origin https://github.com/RockNutria/my-first-blog.git

C:\Users\RockNutria\djangogirls>git push -u origin HEAD
info: please complete authentication in your browser...
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 12 threads
Compressing objects: 100% (17/17), done.
Writing objects: 100% (19/19), 4.48 KiB | 1.49 MiB/s, done.
Total 19 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), done.
remote:
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/RockNutria/my-first-blog/pull/new/master
remote:
To https://github.com/RockNutria/my-first-blog.git
 * [new branch]      HEAD -> master
branch 'master' set up to track 'origin/master'.

C:\Users\RockNutria\djangogirls>python manage.py createsuperuser
Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 22, in <module>
    main()
  File "C:\Users\RockNutria\djangogirls\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

C:\Users\RockNutria\djangogirls>python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 22, in <module>
    main()
  File "C:\Users\RockNutria\djangogirls\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

C:\Users\RockNutria\djangogirls>git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        blog/templates/

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\RockNutria\djangogirls>git add .

C:\Users\RockNutria\djangogirls>git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   blog/templates/blog/post_list.html


C:\Users\RockNutria\djangogirls>git commit -m "changed html"
[master d3d0bbc] changed html
 1 file changed, 10 insertions(+)
 create mode 100644 blog/templates/blog/post_list.html

C:\Users\RockNutria\djangogirls>git push
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 530 bytes | 530.00 KiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/RockNutria/my-first-blog.git
   530f1d6..d3d0bbc  master -> master

C:\Users\RockNutria\djangogirls>python manage.py shell
Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RockNutria\djangogirls\manage.py", line 22, in <module>
    main()
  File "C:\Users\RockNutria\djangogirls\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

C:\Users\RockNutria\djangogirls>            











































Loading console...Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from pythonanywhere) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from pythonanywhere) (2.28.1)
Collecting schema
  Downloading schema-0.7.5-py2.py3-none-any.whl (17 kB)
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting typer
  Downloading typer-0.12.3-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.2/47.2 kB 870.7 kB/s eta 0:00:00
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->pythonanywhere) (2.4.7)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->pythonanywhere) (1.14.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->pythonanywhere) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->pythonanywhere) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->pythonanywhere) (1.26.9)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->pythonanywhere) (2.0.12)
Collecting contextlib2>=0.5.5
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.8/dist-packages (from typer->pythonanywhere) (8.0.3)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.8/dist-packages (from typer->pythonanywhere) (11.2.0)
Collecting shellingham>=1.3.0
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from typer->pythonanywhere) (3.10.0.2)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from rich>=10.11.0->typer->pythonanywhere) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.8/dist-packages (from rich>=10.11.0->typer->pythonanywhere) (2.12.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from rich>=10.11.0->typer->pythonanywhere) (0.4.4)
Building wheels for collected packages: pythonanywhere
  Building wheel for pythonanywhere (setup.py) ... done
  Created wheel for pythonanywhere: filename=pythonanywhere-0.12.1-py3-none-any.whl size=47533 sha256=1db60fdefd8c2f5574efda9126abdd232e10d12f8205a74390c0021cb6efc2df
  Stored in directory: /home/RockNutria/.cache/pip/wheels/f6/3f/70/1a3a7dc9ee42b97787e98808c683dd2441d99232c3b20806c4
Successfully built pythonanywhere
Installing collected packages: tabulate, shellingham, contextlib2, typer, schema, pythonanywhere
Successfully installed contextlib2-21.6.0 pythonanywhere-0.12.1 schema-0.7.5 shellingham-1.5.4 tabulate-0.9.0 typer-0.12.3
17:12 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/RockNutria/my-first-blog.git

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/RockNutria/rocknutria.pythonanywhere.com'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 22 (delta 1), reused 19 (delta 1), pack-reused 0
Unpacking objects: 100% (22/22), 5.29 KiB | 11.00 KiB/s, done.
Traceback (most recent call last):
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 49, in <module>
    main(
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 32, in main
    project.ensure_branch(branch),
  File "/home/RockNutria/.local/lib/python3.8/site-packages/pythonanywhere/django_project.py", line 31, in ensure_branch
    raise SanityException(
pythonanywhere.exceptions.SanityException: There are many branches in your repo. You need to specify which branch to use by adding --branch=<branch> option to the command.
17:15 ~ $ (ola.pythonanywhere.com) $ python manage.py createsuperuser
bash: syntax error near unexpected token `$'
17:16 ~ $ python manage.py createsuperuser
python: can't open file '/home/RockNutria/manage.py': [Errno 2] No such file or directory
17:16 ~ $ cd djangogirls
bash: cd: djangogirls: No such file or directory
17:16 ~ $ python manage.py createsuperuser
python: can't open file '/home/RockNutria/manage.py': [Errno 2] No such file or directory
17:17 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/<your-github-username>/my-first-blog.git
bash: your-github-username: No such file or directory
17:18 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/RockNutria/my-first-blog.git

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/RockNutria/rocknutria.pythonanywhere.com'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 22 (delta 1), reused 19 (delta 1), pack-reused 0
Unpacking objects: 100% (22/22), 5.29 KiB | 16.00 KiB/s, done.
Traceback (most recent call last):
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 49, in <module>
    main(
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 32, in main
    project.ensure_branch(branch),
  File "/home/RockNutria/.local/lib/python3.8/site-packages/pythonanywhere/django_project.py", line 31, in ensure_branch
    raise SanityException(
pythonanywhere.exceptions.SanityException: There are many branches in your repo. You need to specify which branch to use by adding --branch=<branch> option to the command.
17:18 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/RockNutria/my-first-blog

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/RockNutria/rocknutria.pythonanywhere.com'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 22 (delta 1), reused 19 (delta 1), pack-reused 0
Unpacking objects: 100% (22/22), 5.29 KiB | 17.00 KiB/s, done.
Traceback (most recent call last):
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 49, in <module>
    main(
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 32, in main
    project.ensure_branch(branch),
  File "/home/RockNutria/.local/lib/python3.8/site-packages/pythonanywhere/django_project.py", line 31, in ensure_branch
    raise SanityException(
pythonanywhere.exceptions.SanityException: There are many branches in your repo. You need to specify which branch to use by adding --branch=<branch> option to the command.
17:21 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/RockNutria/my-first-blog/tree/master

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/RockNutria/rocknutria.pythonanywhere.com'...
fatal: repository 'https://github.com/RockNutria/my-first-blog/tree/master/' not found
Traceback (most recent call last):
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 49, in <module>
    main(
  File "/home/RockNutria/.local/bin/pa_autoconfigure_django.py", line 31, in main
    project.download_repo(repo_url, nuke=nuke),
  File "/home/RockNutria/.local/lib/python3.8/site-packages/pythonanywhere/django_project.py", line 20, in download_repo
    subprocess.check_call(['git', 'clone', repo, str(self.project_path)])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/RockNutria/my-first-blog/tree/master', '/home/RockNutria/rocknutria.pythonanywhere.com']' returned non-zero exit status 128.
17:21 ~ $ pa_autoconfigure_django.py --python=3.8 https://github.com/RockNutria/my-first-blog

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/RockNutria/rocknutria.pythonanywhere.com'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 19 (delta 1), reused 19 (delta 1), pack-reused 0
Unpacking objects: 100% (19/19), 4.46 KiB | 15.00 KiB/s, done.

< Creating virtualenv with Python3.8 >
   \
    ~<:>>>>>>>>>
created virtual environment CPython3.8.10.final.0-64 in 12872ms
  creator CPython3Posix(dest=/home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/RockNutria/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com/bin/preactivate
virtualenvwrapper.user_scripts creating /home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com/bin/postactivate
virtualenvwrapper.user_scripts creating /home/RockNutria/.virtualenvs/rocknutria.pythonanywhere.com/bin/get_env_details

  _____________________________________________________________________
/                                                                       \
| Pip installing -r                                                     |
| /home/RockNutria/rocknutria.pythonanywhere.com/requirements.txt (this |
| may take a couple of minutes)                                         |
\                                                                       /
  ---------------------------------------------------------------------
   \
    ~<:>>>>>>>>>
Looking in links: /usr/share/pip-wheels
Collecting Django~=3.2.10
  Downloading Django-3.2.25-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 18.4 MB/s eta 0:00:00
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.5.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.1 MB/s eta 0:00:00
Collecting pytz
  Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 11.5 MB/s eta 0:00:00
Collecting asgiref<4,>=3.3.2
  Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Collecting typing-extensions>=4
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Installing collected packages: pytz, typing-extensions, sqlparse, asgiref, Django
Successfully installed Django-3.2.25 asgiref-3.8.1 pytz-2024.1 sqlparse-0.5.0 typing-extensions-4.11.0

< Creating web app via API >
   \
    ~<:>>>>>>>>>

< Adding static files mappings for /static/ and /media/ >
   \
    ~<:>>>>>>>>>

< Updating wsgi file at /var/www/rocknutria_pythonanywhere_com_wsgi.py >
   \
    ~<:>>>>>>>>>

< Updating settings.py >
   \
    ~<:>>>>>>>>>

< Running collectstatic >
   \
    ~<:>>>>>>>>>

128 static files copied to '/home/RockNutria/rocknutria.pythonanywhere.com/static'.

< Running migrate database >
   \
    ~<:>>>>>>>>>
Operations to perform:
  Apply all migrations: admin, auth, blog, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying blog.0001_initial... OK
  Applying sessions.0001_initial... OK
< Reloading rocknutria.pythonanywhere.com via API >
   \
    ~<:>>>>>>>>>
  _____________________________________
/                                       \
| All done!  Your site is now live at   |
| https://rocknutria.pythonanywhere.com |
\                                       /
  -------------------------------------
   \
    ~<:>>>>>>>>>
  ___________________________________________________________________
/                                                                     \
| Starting Bash shell with activated virtualenv in project directory. |
| Press Ctrl+D to exit.                                               |
\                                                                     /
  -------------------------------------------------------------------
   \
    ~<:>>>>>>>>>
(rocknutria.pythonanywhere.com) 17:27 ~/rocknutria.pythonanywhere.com (master)$ python manage.py createsuperuser
Username (leave blank to use 'rocknutria'): 
Email address: zacharymbergman@gmail.com
Password: 
Password (again): 
Superuser created successfully.
(rocknutria.pythonanywhere.com) 17:28 ~/rocknutria.pythonanywhere.com (master)$ ls
blog  db.sqlite3  manage.py  mysite  requirements.txt  static
(rocknutria.pythonanywhere.com) 17:28 ~/rocknutria.pythonanywhere.com (master)$ ls
blog  db.sqlite3  manage.py  mysite  requirements.txt  static
(rocknutria.pythonanywhere.com) 17:40 ~/rocknutria.pythonanywhere.com (master)$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...
System check identified no issues (0 silenced).
April 21, 2024 - 12:45:42
Django version 3.2.25, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
(rocknutria.pythonanywhere.com) 17:45 ~/rocknutria.pythonanywhere.com (master)$ ^C
(rocknutria.pythonanywhere.com) 17:46 ~/rocknutria.pythonanywhere.com (master)$ cd ~/https://rocknutria.pythonanywhere.com
bash: cd: /home/RockNutria/https://rocknutria.pythonanywhere.com: No such file or directory
(rocknutria.pythonanywhere.com) 17:49 ~/rocknutria.pythonanywhere.com (master)$ cd ~/rocknutria.pythonanywhere.com
(rocknutria.pythonanywhere.com) 17:49 ~/rocknutria.pythonanywhere.com (master)$ git pull
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 9), reused 15 (delta 7), pack-reused 0
Unpacking objects: 100% (17/17), 1.45 KiB | 4.00 KiB/s, done.
From https://github.com/RockNutria/my-first-blog
   791db87..d3d0bbc  master     -> origin/master
Updating 791db87..d3d0bbc
error: Your local changes to the following files would be overwritten by merge:
        mysite/settings.py
Please commit your changes or stash them before you merge.
Aborting
(rocknutria.pythonanywhere.com) 17:49 ~/rocknutria.pythonanywhere.com (master)$ 









































https://rocknutria.pythonanywhere.com
















